const API='https://n8n-pi.taild8d05f.ts.net/webhook/dieta-v2';
const AUTH='https://n8n-pi.taild8d05f.ts.net/webhook/dieta-v2-auth';
const TOKEN_KEY='fotoDietaAccessTokenV2';
const PROFILE_KEY='fotoDietaProfileV2';
const state={token:localStorage.getItem(TOKEN_KEY)||'',profile:null,analysis:null,deferredPrompt:null,profiles:[]};
try{state.profile=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch(e){}
const $=id=>document.getElementById(id);
const show=id=>$(id)?.classList.remove('hidden');
const hide=id=>$(id)?.classList.add('hidden');
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const clampPct=(value,target)=>Math.max(0,Math.min(100,target>0?(Number(value||0)/Number(target))*100:0));
const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('')||'?';
const formatDate=raw=>{const d=raw?new Date(raw+'T12:00:00'):new Date();return new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(d)};
const toast=msg=>{const el=$('toast');if(!el)return;el.textContent=msg;show('toast');clearTimeout(toast.t);toast.t=setTimeout(()=>hide('toast'),2600)};
const loading=(on,text='Przetwarzam…',sub='To może potrwać kilka sekund.')=>{if(on){$('loadingText').textContent=text;$('loadingSubtext').textContent=sub;show('loading')}else hide('loading')};
const hideSplash=()=>hide('startSplash');

async function post(url,payload={},file=null){
  let options={method:'POST'};
  if(file){const f=new FormData();Object.entries(payload).forEach(([k,v])=>f.append(k,v));f.append('data',file,file.name||'meal.jpg');options.body=f;}
  else{options.headers={'Content-Type':'application/json'};options.body=JSON.stringify(payload)}
  const r=await fetch(url,options);let data;try{data=await r.json()}catch(e){throw new Error('Nieprawidłowa odpowiedź serwera.')}if(!r.ok||data?.success===false)throw new Error(data?.message||data?.error||'Błąd serwera.');return data;
}
async function api(action,payload={},file=null){if(!state.token)throw new Error('Brak przypisania instalacji.');return post(API,{action,accessToken:state.token,...payload},file)}
function rememberSession(accessToken,userId,displayName){state.token=accessToken;state.profile={userId,displayName};localStorage.setItem(TOKEN_KEY,state.token);localStorage.setItem(PROFILE_KEY,JSON.stringify(state.profile));}

function renderProfileChoices(users=[]){
  state.profiles=users;
  const sel=$('profileSelect'),box=$('profileCards');if(!sel||!box)return;
  sel.innerHTML='';box.innerHTML='';
  if(!users.length){box.innerHTML='<div class="empty">Nie znaleziono aktywnych profili.</div>';return}
  users.forEach((u,index)=>{const o=document.createElement('option');o.value=u.userId;o.textContent=u.displayName;sel.appendChild(o);const b=document.createElement('button');b.type='button';b.className='profile-choice'+(index===0?' active':'');b.dataset.userId=u.userId;b.setAttribute('role','radio');b.setAttribute('aria-checked',index===0?'true':'false');b.innerHTML=`<span class="profile-choice-avatar">${escapeHtml(initials(u.displayName))}</span><span class="profile-choice-copy"><strong>${escapeHtml(u.displayName)}</strong><small>Profil istniejący</small></span><span class="choice-check"><svg viewBox="0 0 24 24"><path d="m6 12 4 4 8-9"/></svg></span>`;b.onclick=()=>selectProfile(u.userId);box.appendChild(b)});
  sel.selectedIndex=0;
}
function selectProfile(userId){const sel=$('profileSelect');sel.value=userId;document.querySelectorAll('.profile-choice').forEach(b=>{const active=b.dataset.userId===userId;b.classList.toggle('active',active);b.setAttribute('aria-checked',active?'true':'false')});}
async function loadProfiles(){try{const d=await post(API,{action:'users_list'});renderProfileChoices(d.users||[])}catch(e){$('authError').textContent=e.message;show('authError')}}

async function claimProfile(){hide('authError');const userId=$('profileSelect').value;const accessPin=$('profilePin').value.trim();if(!userId||!accessPin){$('authError').textContent='Wybierz użytkownika i wpisz PIN.';show('authError');return}loading(true,'Przypisuję profil…','Weryfikuję PIN i zabezpieczam tę instalację.');try{const d=await post(AUTH,{userId,accessPin});rememberSession(d.accessToken,d.userId,$('profileSelect').selectedOptions[0]?.textContent||d.userId);await enterApp()}catch(e){$('authError').textContent=e.message;show('authError')}finally{loading(false)}}
async function createUser(){hide('authError');const displayName=$('newName').value.trim(),accessPin=$('newPin').value.trim();if(displayName.length<2){$('authError').textContent='Podaj imię lub nazwę użytkownika.';show('authError');return}if(!/^\d{4,8}$/.test(accessPin)){$('authError').textContent='PIN musi mieć 4–8 cyfr.';show('authError');return}const payload={action:'user_create',displayName,accessPin,dailyCalorieTarget:$('newCalories').value,dailyProteinTarget:$('newProtein').value,dailyCarbsTarget:$('newCarbs').value,dailyFatTarget:$('newFat').value};loading(true,'Tworzę profil…','Zapisuję profil, cele dzienne i przypisuję urządzenie.');try{const created=await post(API,payload);const userId=created.user?.userId;if(!userId)throw new Error('Nie udało się utworzyć profilu.');const auth=await post(AUTH,{userId,accessPin});rememberSession(auth.accessToken,userId,created.user?.displayName||displayName);await enterApp()}catch(e){$('authError').textContent=e.message;show('authError')}finally{loading(false)}}

function nav(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));const map={today:'viewToday',add:'viewAdd',favorites:'viewFavorites',history:'viewHistory',profile:'viewProfile'};$(map[name])?.classList.add('active');if(name==='today')loadDashboard();if(name==='favorites')loadFavorites();if(name==='history')loadHistory();if(name==='profile')loadSettings();window.scrollTo({top:0,behavior:'smooth'});}
function nutrition(m){return `<div class="nutrition"><span>${Math.round(m.calories||0)} kcal</span><span>B ${Math.round(m.protein||0)} g</span><span>W ${Math.round(m.carbs||0)} g</span><span>T ${Math.round(m.fat||0)} g</span></div>`}
function setProgress(id,value,target,percentId){const p=clampPct(value,target);const bar=$(id);if(bar)bar.style.width=`${p}%`;if(percentId&&$(percentId))$(percentId).textContent=`${Math.round(p)}%`;return p}
async function loadDashboard(){try{const d=await api('dashboard');const name=state.profile?.displayName||'';$('welcome').textContent=`Dzień dobry${name?`, ${name}`:''}`;$('profileName').textContent=name||d.userId;$('profileAvatar').textContent=initials(name||d.userId);$('todayDate').textContent=d.date||'';$('headerDate').textContent=formatDate(d.date);$('mealCount').textContent=`${d.count||0} ${Number(d.count||0)===1?'posiłek':'posiłków'}`;const c=d.consumed||{},t=d.targets||{},r=d.remaining||{};$('kcalConsumed').textContent=Math.round(c.calories||0);$('kcalTarget').textContent=Math.round(t.calories||0);$('kcalRemaining').textContent=`${Math.max(0,Math.round(r.calories??(Number(t.calories||0)-Number(c.calories||0))))} kcal`;const pct=setProgress('kcalBar',c.calories,t.calories);$('kcalPercent').textContent=`${Math.round(pct)}%`;$('kcalPercent').closest('.percent-ring')?.style.setProperty('--pct',`${pct}%`);$('proteinConsumed').textContent=Math.round(c.protein||0);$('carbsConsumed').textContent=Math.round(c.carbs||0);$('fatConsumed').textContent=Math.round(c.fat||0);$('proteinTarget').textContent=`cel ${Math.round(t.protein||0)} g`;$('carbsTarget').textContent=`cel ${Math.round(t.carbs||0)} g`;$('fatTarget').textContent=`cel ${Math.round(t.fat||0)} g`;setProgress('proteinBar',c.protein,t.protein,'proteinPercent');setProgress('carbsBar',c.carbs,t.carbs,'carbsPercent');setProgress('fatBar',c.fat,t.fat,'fatPercent');const box=$('todayMeals');box.innerHTML='';if(!(d.meals||[]).length){box.innerHTML='<div class="empty">Nie masz jeszcze zapisanych posiłków na dziś.<br>Dodaj pierwszy posiłek, gdy będziesz gotowy.</div>';return}(d.meals||[]).forEach(m=>{const a=document.createElement('article');a.innerHTML=`<div class="meal-head"><div><h3>${escapeHtml(m.description)}</h3><div class="meta">Posiłek ${m.mealNo}</div></div><button class="danger-link" data-del="${escapeHtml(m.mealId)}">Usuń</button></div>${nutrition(m)}`;box.appendChild(a)});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteMeal(b.dataset.del))}catch(e){toast(e.message)}}
async function deleteMeal(mealId){if(!confirm('Usunąć ten posiłek?'))return;loading(true,'Usuwam posiłek…','Aktualizuję dzisiejszy bilans.');try{await api('meal_delete',{mealId});toast('Posiłek usunięty');await loadDashboard()}catch(e){toast(e.message)}finally{loading(false)}}

function renderAnalysis(a){state.analysis=a;$('analysisDescription').value=a.description||'';$('analysisCalories').value=Math.round(a.calories||0);const conf=String(a.confidence||'').toLowerCase();$('analysisConfidence').textContent=conf==='high'?'Wysoka pewność':conf==='medium'?'Średnia pewność':conf==='low'?'Niska pewność':a.confidence||'';$('analysisItems').innerHTML=(a.items||[]).map(x=>`<div class="analysis-item"><span>${escapeHtml(x.namePl)} · ${Math.round(x.grams||0)} g</span><strong>${Math.round(x.calories||0)} kcal</strong></div>`).join('');show('analysisPanel');setTimeout(()=>$('analysisPanel')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}
async function analyzeText(){const text=$('mealText').value.trim();if(!text)return toast('Wpisz opis posiłku.');loading(true,'Analizuję posiłek…','Rozpoznaję składniki i szacuję wartości odżywcze.');try{const d=await api('analyze_text',{text});renderAnalysis(d.analysis)}catch(e){toast(e.message)}finally{loading(false)}}
async function analyzePhoto(file){if(!file)return;loading(true,'Analizuję zdjęcie…','AI rozpoznaje składniki i oblicza wartości odżywcze.');try{const d=await api('analyze_photo',{},file);renderAnalysis(d.analysis)}catch(e){toast(e.message)}finally{loading(false);$('photoInput').value=''}}
async function saveMeal(){if(!state.analysis)return;loading(true,'Zapisuję posiłek…','Aktualizuję dzisiejszy bilans.');try{await api('meal_save',{analysisJson:JSON.stringify(state.analysis),description:$('analysisDescription').value.trim(),calories:$('analysisCalories').value});state.analysis=null;hide('analysisPanel');$('mealText').value='';toast('Posiłek zapisany');nav('today')}catch(e){toast(e.message)}finally{loading(false)}}
async function saveFavorite(){if(!state.analysis)return;loading(true,'Dodaję do ulubionych…','Zapisuję gotowy posiłek do szybkiego użycia.');try{await api('favorite_add',{analysisJson:JSON.stringify(state.analysis),description:$('analysisDescription').value.trim(),calories:$('analysisCalories').value});toast('Dodano do ulubionych')}catch(e){toast(e.message)}finally{loading(false)}}

async function loadFavorites(){try{const d=await api('favorites_list');const box=$('favoritesList');box.innerHTML='';if(!(d.favorites||[]).length){box.innerHTML='<div class="empty">Brak ulubionych posiłków.<br>Po analizie posiłku możesz zapisać go tutaj.</div>';return}(d.favorites||[]).forEach(f=>{const a=document.createElement('article');a.innerHTML=`<div class="fav-head"><div><h3>${escapeHtml(f.description)}</h3><div class="meta">${escapeHtml((f.addedAt||'').slice(0,10))}</div></div><button class="danger-link" data-fdel="${escapeHtml(f.favoriteId)}">Usuń</button></div>${nutrition(f)}<button class="small" data-use="${escapeHtml(f.favoriteId)}">Dodaj jako bieżący posiłek</button>`;a.dataset.favorite=JSON.stringify(f);box.appendChild(a)});box.querySelectorAll('[data-fdel]').forEach(b=>b.onclick=()=>deleteFavorite(b.dataset.fdel));box.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const f=JSON.parse(b.closest('article').dataset.favorite);state.analysis={description:f.description,items:f.items,calories:f.calories,protein:f.protein,carbs:f.carbs,fat:f.fat,source:`Ulubione · ${f.source||'Dieta V2'}`,confidence:f.confidence||'high'};nav('add');renderAnalysis(state.analysis)})}catch(e){toast(e.message)}}
async function deleteFavorite(favoriteId){if(!confirm('Usunąć z ulubionych?'))return;loading(true,'Usuwam z ulubionych…','Aktualizuję listę zapisanych posiłków.');try{await api('favorite_delete',{favoriteId});toast('Usunięto z ulubionych');await loadFavorites()}catch(e){toast(e.message)}finally{loading(false)}}

function renderHistoryStrip(days=[]){const strip=$('historyDaysStrip');strip.innerHTML='';if(!days.length){$('historyMonth').textContent='';return}const latest=new Date(days[0].date+'T12:00:00');$('historyMonth').textContent=new Intl.DateTimeFormat('pl-PL',{month:'long',year:'numeric'}).format(latest);days.slice(0,14).forEach((day,index)=>{const dt=new Date(day.date+'T12:00:00');const b=document.createElement('button');b.type='button';b.className='day-chip'+(index===0?' active':'');b.innerHTML=`<small>${new Intl.DateTimeFormat('pl-PL',{weekday:'short'}).format(dt).replace('.','')}</small><strong>${dt.getDate()}</strong>`;b.onclick=()=>document.querySelector(`[data-history-date="${CSS.escape(day.date)}"]`)?.scrollIntoView({behavior:'smooth',block:'start'});strip.appendChild(b)})}
async function loadHistory(){loading(true,'Ładuję historię…','Pobieram zapisane dni i ich podsumowania.');try{const d=await api('history');const box=$('historyList');box.innerHTML='';renderHistoryStrip(d.days||[]);if(!(d.days||[]).length){box.innerHTML='<div class="empty">Brak historii.<br>Zapisane dni pojawią się tutaj automatycznie.</div>';return}(d.days||[]).forEach(day=>{const a=document.createElement('article');a.dataset.historyDate=day.date;const meals=(day.meals||[]).map(m=>`<div><span>${m.mealNo}. ${escapeHtml(m.description)}</span><strong>${Math.round(m.calories||0)} kcal</strong></div>`).join('');a.innerHTML=`<div class="history-head"><div><h3>${escapeHtml(day.date)}</h3><div class="meta">${Math.round(day.totals?.calories||0)} / ${Math.round(day.targets?.calories||0)} kcal</div></div><button class="danger-link" data-ddel="${escapeHtml(day.date)}">Usuń dzień</button></div>${nutrition(day.totals||{})}<div class="history-meals">${meals}</div>`;box.appendChild(a)});box.querySelectorAll('[data-ddel]').forEach(b=>b.onclick=()=>deleteDay(b.dataset.ddel))}catch(e){toast(e.message)}finally{loading(false)}}
async function deleteDay(date){if(!confirm(`Usunąć cały dzień ${date}?`))return;loading(true,'Usuwam dzień…','Kasuję zapisane posiłki z wybranego dnia.');try{await api('day_delete',{date});toast('Dzień usunięty');await loadHistory()}catch(e){toast(e.message)}finally{loading(false)}}

async function loadSettings(){loading(true,'Ładuję ustawienia…','Pobieram cele przypisane do Twojego profilu.');try{const d=await api('settings_get');$('setCalories').value=d.settings.dailyCalorieTarget;$('setProtein').value=d.settings.dailyProteinTarget;$('setCarbs').value=d.settings.dailyCarbsTarget;$('setFat').value=d.settings.dailyFatTarget;const name=state.profile?.displayName||'Profil';$('profileName').textContent=name;$('profileAvatar').textContent=initials(name);$('profileSubline').textContent='Ta instalacja jest trwale przypisana do tego profilu.'}catch(e){toast(e.message)}finally{loading(false)}}
async function saveSettings(){loading(true,'Zapisuję ustawienia…','Aktualizuję cele dzienne i ich historię.');try{await api('settings_update',{dailyCalorieTarget:$('setCalories').value,dailyProteinTarget:$('setProtein').value,dailyCarbsTarget:$('setCarbs').value,dailyFatTarget:$('setFat').value});toast('Cele zapisane');await loadSettings()}catch(e){toast(e.message)}finally{loading(false)}}

function installSetup(){const standalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;const install=async()=>{if(standalone())return;if(state.deferredPrompt){state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;hide('installBtn');hide('installFirstBtn');return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);alert(ios?'Na iPhonie: w Safari wybierz Udostępnij, a następnie „Dodaj do ekranu początkowego”.':'Otwórz menu przeglądarki i wybierz „Zainstaluj aplikację” lub „Dodaj do ekranu głównego”.')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;if(!standalone())show('installBtn')});window.addEventListener('appinstalled',()=>{hide('installBtn');hide('installFirstBtn')});$('installBtn').onclick=install;$('installFirstBtn').onclick=install;if(standalone()){hide('installBtn');hide('installFirstBtn')}}
async function enterApp(){hide('authScreen');show('app');$('profileName').textContent=state.profile?.displayName||'Profil';$('profileAvatar').textContent=initials(state.profile?.displayName||'Profil');hideSplash();await loadDashboard()}
async function init(){document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));$('claimProfileBtn').onclick=claimProfile;$('createUserBtn').onclick=createUser;$('showTextBtn').onclick=()=>{show('textPanel');setTimeout(()=>$('textPanel')?.scrollIntoView({behavior:'smooth',block:'start'}),50)};$('analyzeTextBtn').onclick=analyzeText;$('photoInput').onchange=e=>analyzePhoto(e.target.files?.[0]);$('saveMealBtn').onclick=saveMeal;$('saveFavoriteBtn').onclick=saveFavorite;$('saveSettingsBtn').onclick=saveSettings;installSetup();const online=()=>navigator.onLine?hide('offline'):show('offline');window.addEventListener('online',online);window.addEventListener('offline',online);online();if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js?v=20260814-7');reg.update().catch(()=>{})}catch(e){}}
  if(state.token){try{await api('settings_get');await enterApp();return}catch(e){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(PROFILE_KEY);state.token='';state.profile=null;toast('Sesja wygasła. Przypisz instalację ponownie.')}}show('authScreen');hideSplash();await loadProfiles()}
document.addEventListener('DOMContentLoaded',init);
