(() => {
  'use strict';
  const THEME_KEY_PREFIX='dietaV2Theme:'; const VALID=new Set(['dark','light']); let currentTheme='dark',saving=false;
  function ensureStyles(){if(document.getElementById('themeLightStyles'))return;const link=document.createElement('link');link.id='themeLightStyles';link.rel='stylesheet';link.href='./theme-light.css?v=20260815-theme1';document.head.appendChild(link)}
  function profileId(){return String(state?.profile?.userId||'').trim()} function storageKey(){const id=profileId();return id?`${THEME_KEY_PREFIX}${id}`:''} function localTheme(){const k=storageKey();if(!k)return'dark';const v=String(localStorage.getItem(k)||'').toLowerCase();return VALID.has(v)?v:'dark'} function rememberLocal(t){const k=storageKey();if(k&&VALID.has(t))localStorage.setItem(k,t)}
  function applyTheme(theme,{remember=true}={}){ensureStyles();const next=VALID.has(theme)?theme:'dark';currentTheme=next;const app=document.getElementById('app');if(app)app.dataset.theme=next;document.body.classList.toggle('theme-light-active',next==='light'&&!app?.classList.contains('hidden'));const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',next==='light'?'#fbfaf7':'#071014');if(remember)rememberLocal(next);document.querySelectorAll('[data-theme-choice]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.themeChoice===currentTheme?'true':'false'))}
  function forceAuthDark(){currentTheme='dark';const app=document.getElementById('app');if(app)app.dataset.theme='dark';document.body.classList.remove('theme-light-active');const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content','#071014')}
  function ensureUi(){ensureStyles();if(document.getElementById('themePanel'))return;const profile=document.getElementById('viewProfile'),goals=profile?.querySelector('.goals-panel');if(!profile||!goals)return;const panel=document.createElement('div');panel.id='themePanel';panel.className='panel glass-card theme-panel';panel.innerHTML=`<div class="panel-heading compact"><span class="panel-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3a9 9 0 1 0 9 9 7 7 0 0 1-9-9Z"/></svg></span><div><h3>Motyw aplikacji</h3><p>Wybierz wygląd używany po zalogowaniu. Ustawienie jest przypisane do Twojego profilu.</p></div></div><div class="theme-choice-grid" role="group"><button class="theme-choice" type="button" data-theme-choice="dark">Motyw ciemny</button><button class="theme-choice" type="button" data-theme-choice="light">Motyw jasny</button></div>`;goals.insertAdjacentElement('beforebegin',panel);panel.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>changeTheme(b.dataset.themeChoice)));applyTheme(currentTheme,{remember:false})}
  async function syncTheme(){if(!state?.token||!profileId()){forceAuthDark();return}applyTheme(localTheme(),{remember:false});try{const data=await api('theme_get');applyTheme(VALID.has(data?.uiTheme)?data.uiTheme:'dark')}catch(e){console.warn('Nie udało się zsynchronizować motywu:',e)}}
  async function changeTheme(theme){if(!VALID.has(theme)||saving||theme===currentTheme)return;const previous=currentTheme;applyTheme(theme);saving=true;try{await api('theme_update',{uiTheme:theme});toast(theme==='light'?'Włączono motyw jasny':'Włączono motyw ciemny')}catch(e){applyTheme(previous);toast(e?.message||'Nie udało się zapisać motywu.')}finally{saving=false}}
  const baseEnterApp=enterApp;enterApp=async function(...args){if(state?.profile?.userId)applyTheme(localTheme(),{remember:false});const result=await baseEnterApp(...args);ensureUi();syncTheme();return result};const baseClearSession=clearSession;clearSession=function(...args){const r=baseClearSession(...args);forceAuthDark();return r};const baseLoadSettings=loadSettings;loadSettings=async function(...args){const r=await baseLoadSettings(...args);ensureUi();return r};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureUi,{once:true});else ensureUi();
})();

(() => {
  'use strict';
  const PROFILE_DELETE_API=API.replace(/\/dieta-v2$/,'/dieta-v2-profile-delete'); let deleting=false,deleteViewportCleanup=null;
  function setAuthError(message){const e=document.getElementById('authError');if(e){e.textContent=message;e.classList.remove('hidden')}}
  function ensurePinConfirmation(){const pin=document.getElementById('newPin');if(!pin)return;if(!document.getElementById('newPinConfirm')){const label=document.createElement('label');label.textContent='Powtórz PIN';const input=document.createElement('input');input.id='newPinConfirm';input.type='password';input.inputMode='numeric';input.maxLength=8;input.autocomplete='new-password';input.placeholder='Powtórz 4–8 cyfr';label.appendChild(input);pin.closest('label')?.insertAdjacentElement('afterend',label)}const button=document.getElementById('createUserBtn');if(!button||button.dataset.pinConfirmGuard==='1')return;button.dataset.pinConfirmGuard='1';button.addEventListener('click',event=>{const a=String(document.getElementById('newPin')?.value||'').trim(),b=String(document.getElementById('newPinConfirm')?.value||'').trim();if(!/^\d{4,8}$/.test(b)||a!==b){event.preventDefault();event.stopImmediatePropagation();setAuthError('PIN-y nie są zgodne. Wprowadź ten sam PIN w obu polach.');document.getElementById('newPinConfirm')?.focus()}},true)}
  function ensureDeleteStyles(){if(document.getElementById('profileDeleteStyles'))return;const style=document.createElement('style');style.id='profileDeleteStyles';style.textContent=`.profile-danger-panel{border-color:rgba(244,91,91,.28)!important}.profile-danger-panel h3{color:#ffb0b0}.profile-delete-btn{width:100%;border:1px solid rgba(244,91,91,.5);background:rgba(244,91,91,.1);color:#ffd0d0;border-radius:14px;padding:13px 16px;font:700 15px/1.2 system-ui,sans-serif;cursor:pointer}.profile-delete-modal{position:fixed;z-index:12000;left:0;right:0;top:0;height:var(--profile-delete-vvh,100dvh);display:flex;align-items:flex-start;justify-content:center;overflow-y:auto;overscroll-behavior:contain;padding:max(16px,env(safe-area-inset-top)) 16px max(16px,env(safe-area-inset-bottom));background:rgba(2,8,11,.82);backdrop-filter:blur(8px);-webkit-overflow-scrolling:touch}.profile-delete-modal.hidden{display:none!important}.profile-delete-card{width:min(100%,460px);max-height:calc(var(--profile-delete-vvh,100dvh) - 32px);overflow-y:auto;overscroll-behavior:contain;scroll-padding-block:80px;margin:auto 0;border:1px solid rgba(244,91,91,.32);border-radius:20px;padding:22px;background:#0b171c;box-shadow:0 24px 80px rgba(0,0,0,.5);-webkit-overflow-scrolling:touch}.profile-delete-card h3{margin:0 0 10px;color:#ffd1d1}.profile-delete-card p,.profile-delete-card li{color:#c8d8da;line-height:1.5}.profile-delete-card ul{padding-left:20px}.profile-delete-card label{display:grid;gap:7px}.profile-delete-card input{scroll-margin-block:90px}.profile-delete-actions{position:sticky;bottom:-1px;display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px;padding:12px 0 2px;background:linear-gradient(180deg,rgba(11,23,28,0),#0b171c 28%)}.profile-delete-cancel,.profile-delete-confirm{min-height:48px;border-radius:13px;padding:12px 14px;font-weight:800;cursor:pointer}.profile-delete-cancel{border:1px solid rgba(255,255,255,.15);background:#162328;color:#e6f2f1}.profile-delete-confirm{border:1px solid rgba(244,91,91,.6);background:#8e2f35;color:#fff}@media(max-height:620px){.profile-delete-card{padding:18px}.profile-delete-card ul{margin-block:10px}.profile-delete-actions{margin-top:12px}}`;document.head.appendChild(style)}
  function syncDeleteViewport(){const modal=document.getElementById('profileDeleteModal');if(!modal||modal.classList.contains('hidden'))return;const viewport=window.visualViewport;const height=Math.max(280,Math.round(viewport?.height||window.innerHeight));const offsetTop=Math.max(0,Math.round(viewport?.offsetTop||0));modal.style.setProperty('--profile-delete-vvh',`${height}px`);modal.style.top=`${offsetTop}px`;modal.style.height=`${height}px`}
  function bindDeleteViewport(){deleteViewportCleanup?.();const sync=()=>{syncDeleteViewport();if(document.activeElement?.id==='profileDeletePin')setTimeout(()=>document.activeElement?.scrollIntoView({block:'center',behavior:'smooth'}),40)};window.addEventListener('resize',sync);window.visualViewport?.addEventListener('resize',sync);window.visualViewport?.addEventListener('scroll',sync);deleteViewportCleanup=()=>{window.removeEventListener('resize',sync);window.visualViewport?.removeEventListener('resize',sync);window.visualViewport?.removeEventListener('scroll',sync);deleteViewportCleanup=null};sync()}
  function closeDeleteModal(){const modal=document.getElementById('profileDeleteModal');modal?.classList.add('hidden');deleteViewportCleanup?.();if(modal){modal.style.removeProperty('--profile-delete-vvh');modal.style.removeProperty('top');modal.style.removeProperty('height')}document.body.classList.remove('modal-open');const pin=document.getElementById('profileDeletePin');if(pin)pin.value='';const e=document.getElementById('profileDeleteError');if(e){e.textContent='';e.classList.add('hidden')}}
  function focusDeletePin(){const pin=document.getElementById('profileDeletePin');if(!pin)return;try{pin.focus({preventScroll:true})}catch(_){pin.focus()}setTimeout(()=>{syncDeleteViewport();pin.scrollIntoView({block:'center',behavior:'smooth'})},180)}
  function openDeleteModal(){const modal=document.getElementById('profileDeleteModal');modal?.classList.remove('hidden');document.body.classList.add('modal-open');bindDeleteViewport();requestAnimationFrame(()=>focusDeletePin())}
  async function deleteProfile(){if(deleting||!state?.token)return;const pin=String(document.getElementById('profileDeletePin')?.value||'').trim(),error=document.getElementById('profileDeleteError');if(!/^\d{4,8}$/.test(pin)){if(error){error.textContent='Wpisz poprawny PIN 4–8 cyfr.';error.classList.remove('hidden')}return}deleting=true;const confirm=document.getElementById('profileDeleteConfirm'),launch=document.getElementById('deleteProfileBtn');if(confirm)confirm.disabled=true;if(launch)launch.disabled=true;loading(true,'Usuwam profil…','Usuwam dane powiązane z profilem i zapisuję wyłącznie anonimowe agregaty statystyczne.');const deletedUserId=String(state?.profile?.userId||'');try{await post(PROFILE_DELETE_API,{accessToken:state.token,accessPin:pin});if(deletedUserId)localStorage.removeItem(`dietaV2Theme:${deletedUserId}`);closeDeleteModal();clearSession();hide('app');document.getElementById('authScreen')?.classList.remove('install-only');show('authScreen');if(document.getElementById('profileLogin'))document.getElementById('profileLogin').value='';if(document.getElementById('profilePin'))document.getElementById('profilePin').value='';await loadProfiles();toast('Profil i dane powiązane z kontem zostały usunięte.')}catch(err){if(error){error.textContent=err?.message||'Nie udało się usunąć profilu.';error.classList.remove('hidden')}}finally{deleting=false;if(confirm)confirm.disabled=false;if(launch)launch.disabled=false;loading(false)}}
  function ensureDeleteUi(){ensureDeleteStyles();const themePanel=document.getElementById('themePanel');if(!themePanel||document.getElementById('profileDangerPanel'))return;const panel=document.createElement('div');panel.id='profileDangerPanel';panel.className='panel glass-card profile-danger-panel';panel.innerHTML=`<div class="panel-heading compact"><div><h3>Usuń profil</h3><p>Usuń profil i dane pozwalające powiązać historię z kontem.</p></div></div><button id="deleteProfileBtn" class="profile-delete-btn" type="button">Usuń profil</button>`;themePanel.insertAdjacentElement('afterend',panel);if(!document.getElementById('profileDeleteModal')){const modal=document.createElement('div');modal.id='profileDeleteModal';modal.className='profile-delete-modal hidden';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML=`<div class="profile-delete-card"><h3>Usunąć profil?</h3><p>Operacji nie można cofnąć. Zniknie profil i jego historia.</p><ul><li>dane identyfikujące, sesje, ustawienia, posiłki, nawodnienie, zgody i pozostałe dane powiązane z profilem zostaną usunięte,</li><li>wybrane dane zostaną zachowane wyłącznie jako niepowiązane anonimowe agregaty statystyczne,</li><li>jeżeli istnieje zakup Google Play, rekord transakcyjny zostanie odłączony od profilu i może pozostać technicznie maksymalnie do 180 dni po wygaśnięciu,</li><li>usunięcie profilu nie anuluje subskrypcji Google Play.</li></ul><label>Potwierdź PIN<input id="profileDeletePin" type="password" inputmode="numeric" maxlength="8" autocomplete="current-password" placeholder="Wpisz PIN"></label><p id="profileDeleteError" class="profile-delete-error hidden" role="alert"></p><div class="profile-delete-actions"><button id="profileDeleteCancel" class="profile-delete-cancel" type="button">Anuluj</button><button id="profileDeleteConfirm" class="profile-delete-confirm" type="button">Usuń profil i dane</button></div></div>`;document.body.appendChild(modal);document.getElementById('profileDeleteCancel')?.addEventListener('click',closeDeleteModal);document.getElementById('profileDeleteConfirm')?.addEventListener('click',deleteProfile);document.getElementById('profileDeletePin')?.addEventListener('focus',()=>setTimeout(()=>{syncDeleteViewport();document.getElementById('profileDeletePin')?.scrollIntoView({block:'center',behavior:'smooth'})},180));modal.addEventListener('click',e=>{if(e.target===modal&&!deleting)closeDeleteModal()})}document.getElementById('deleteProfileBtn')?.addEventListener('click',openDeleteModal)}
  function ensureAccountUi(){ensurePinConfirmation();ensureDeleteUi()} const baseEnterAppAccount=enterApp;enterApp=async function(...args){const r=await baseEnterAppAccount(...args);ensureAccountUi();return r};const baseLoadSettingsAccount=loadSettings;loadSettings=async function(...args){const r=await baseLoadSettingsAccount(...args);ensureAccountUi();return r};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureAccountUi,{once:true});else ensureAccountUi();
})();
